<a href="https://colab.research.google.com/github/Divyam-Chauhan/Numpy-Pandas-Seaborn_Practice/blob/main/Measures_of_Central_Tendency.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import seaborn as sns
import pandas as pd
import numpy as np

# Load the tips dataset
tips = sns.load_dataset('tips')

In [6]:
tips.head(100)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
..         ...   ...     ...    ...  ...     ...   ...
95       40.17  4.73    Male    Yes  Fri  Dinner     4
96       27.28  4.00    Male    Yes  Fri  Dinner     2
97       12.03  1.50    Male    Yes  Fri  Dinner     2
98       21.01  3.00    Male    Yes  Fri  Dinner     2
99       12.46  1.50    Male     No  Fri  Dinner     2

[100 rows x 7 columns]

In [7]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [8]:
total_bill_mean = np.mean(tips['total_bill'])

print(f"mean of bills: {total_bill_mean}")

mean of bills: 19.78594262295082

In [9]:
total_tip_mean = tips['tip'].mean()

print(f"mean_of_tips: {total_tip_mean}")

mean_of_tips: 2.99827868852459

In [10]:
total_bill_median = np.median(tips["total_bill"])

print(f"median_of_bills: {total_bill_median}")

median_of_bills: 17.795

In [11]:
tip_median = tips["tip"].median()

print(f"median_of_tips: {tip_median}")

median_of_tips: 2.9

In [12]:
tips['tip'].value_counts()

tip
2.00    33
3.00    23
4.00    12
2.50    10
5.00    10
        ..
1.47     1
1.17     1
4.67     1
5.92     1
1.75     1
Name: count, Length: 123, dtype: int64

In [13]:
tip_mode = tips['tip'].mode()

print(f"mode of tips: {tip_mode[0]}")

mode of tips: 2.0

In [14]:
mode_sex = tips['sex'].mode()

print(f"mode_of_sex: {mode_sex[0]}")

mode_of_sex: Male

In [15]:
mode_day = tips['day'].mode()

print(f"mode_of_day: {mode_day[0]}")

mode_of_day: Sat

In [16]:
mode_time = tips['time'].mode()

print(f"mode_of_time: {mode_time[0]}")

mode_of_time: Dinner

# **Starting with Measures of Dispersion:**

**Range:**

In [17]:
total_bill_range = tips['total_bill'].max() - tips['total_bill'].min()

print(f"Range of total_bill = {total_bill_range}")
print(f"Maximum bill = {tips['total_bill'].max()}")
print(f"Minimum bill = {tips['total_bill'].min()}")

Range of total_bill = 47.74
Maximum bill = 50.81
Minimum bill = 3.07

In [18]:
total_tips_range = tips['tip'].max() - tips['tip'].min()

print(f"Range of total tips = {total_tips_range}")
print(f"Maximum tip = {tips['tip'].max()}")
print(f"Minimum tip = {tips['tip'].min()}")

Range of total tips = 9.0
Maximum tip = 10.0
Minimum tip = 1.0

# Variance:

Pandas Variance and Numpy variance is slightly different because pandas finds Sample variance (denominator is n-1) and numpy finds Variance (denominator is n)

Variance = σ² = Σ(Xᵢ − μ)²

Where:
- σ² = Variance
- n = Total number of observations
- μ = Mean

Sample Variance = s² = Σ(Xᵢ − x̅)² / (n-1)

Where:
- s² = Variance
- n = Total number of observations
- x̅ = Mean of the sample

In [19]:
np_total_bill_variance = np.var(tips['total_bill'])
print(f"Numpy Variance of total_bill = {np_total_bill_variance}")

Numpy Variance of total_bill = 78.92813148851113

In [20]:
pd_total_bill_variance = tips['total_bill'].var()
print(f"pandas Variance of total bill = {pd_total_bill_variance}")

pandas Variance of total bill = 79.25293861397826

# Standard Deviation

In [21]:
tips_std = tips['tip'].std()
print(f"Standard Deviation of tips = {tips_std}")

Standard Deviation of tips = 1.3836381890011826

In [22]:
np_tips_std = np.std(tips['tip'])
print(f"Numpy Standard Deviation of tips = {np_tips_std}")

Numpy Standard Deviation of tips = 1.3807999538298958

# Interquartile Range (IQR):

In [23]:
q1_totalBill = tips['total_bill'].quantile(0.25)
q2_totalBill = tips['total_bill'].quantile(0.50)
q3_totalBill = tips['total_bill'].quantile(0.75)

print(f"First Quartile of total Bill = {q1_totalBill}")
print(f"Second Quartile/Median of Total Bill = {q2_totalBill}")
print(f"Third Quartile of Total Bill = {q3_totalBill}")

First Quartile of total Bill = 13.3475
Second Quartile/Median of Total Bill = 17.795
Third Quartile of Total Bill = 24.127499999999998

In [25]:
q1_tips = tips['tip'].quantile(0.25)
q2_tips = tips['tip'].quantile(0.50)
q3_tips = tips['tip'].quantile(0.75)

print(f"First Quartile of tips = {q1_tips}")
print(f"Second Quartile/Median of tips = {q2_tips}")
print(f"Third Quartile of Tips = {q3_tips}")

First Quartile of tips = 2.0
Second Quartile/Median of tips = 2.9
Third Quartile of Tips = 3.5625

**All of These Measures could be done by one inbuilt Function as well:**

dbName.describe()

In [32]:
print("\nDescription of the tips Dataset: \n", tips.describe())

Description of the tips Dataset:
        total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000